### ISSUE TITLE
A Repo for Localization To Urdu or any other lang

### ISSUE THREAD

**Issue by emadehsan** [Mukarrim/AndroidLocalizationUrdu#1]
Hello @Mukarrim,  You might like to look at https://github.com/emadehsan/ieighteen for automating localization to Urdu or any language that you might like

**Comment by Mukarrim** [comment]
@emadehsan Thank you for mentioning it, but my work is more related to providing a running/working application which implements localization.
From what I see your providing strings and structure of string files for conversion.

**Comment by emadehsan** [comment]
I see. If you would like to contribute or give suggestion on my project, It'd be appreciated. Since the goal here is to enable and spread awareness in Pakistani developers about Localization.

Regards.
